name: Trigger-DevOps-Build
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger Staging'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://ssw.visualstudio.com/SSW.People'
        azure-pipeline-name: 'Staging' 
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          export AZURE_DEVOPS_EXT_PAT=${{ secrets.AZURE_DEVOPS_TOKEN }}
          chmod +x $GITHUB_WORKSPACE/.github/workflows/build-production.sh
          $GITHUB_WORKSPACE/.github/workflows/build-production.sh